const INTEGRATION_DEFAULT_USER = 'admin';
const INTEGRATION_BALENA_API_OAUTH_BASE_URL = 'https://api.balena-cloud.com';
const INTEGRATION_BALENA_API_PRIVATE_KEY = '';
const INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION = '';

export {
	INTEGRATION_DEFAULT_USER,
	INTEGRATION_BALENA_API_OAUTH_BASE_URL,
	INTEGRATION_BALENA_API_PRIVATE_KEY,
	INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION,
};
