const INTEGRATION_DEFAULT_USER = 'admin';
const INTEGRATION_BALENA_API_APP_ID = 'foobar';
const INTEGRATION_BALENA_API_APP_SECRET = 'foobar';
const INTEGRATION_BALENA_API_OAUTH_BASE_URL = 'https://api.balena-cloud.com';
const INTEGRATION_BALENA_API_PRIVATE_KEY = '';
const INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION = '';
const INTEGRATION_BALENA_API_PUBLIC_KEY_STAGING = 'foobar';
const INTEGRATION_OUTREACH_APP_ID = 'changeme';
const INTEGRATION_OUTREACH_APP_SECRET = 'changeme';
const INTEGRATION_FLOWDOCK_TOKEN = 'ncuu6aefw39ymw56wi7iqhsn4mvetq7w';
const INTEGRATION_FLOWDOCK_SIGNATURE_KEY = 'uNyDWFgL2Gw5NPnsEc9LM';

export {
	INTEGRATION_DEFAULT_USER,
	INTEGRATION_BALENA_API_APP_ID,
	INTEGRATION_BALENA_API_APP_SECRET,
	INTEGRATION_BALENA_API_OAUTH_BASE_URL,
	INTEGRATION_BALENA_API_PRIVATE_KEY,
	INTEGRATION_BALENA_API_PUBLIC_KEY_PRODUCTION,
	INTEGRATION_BALENA_API_PUBLIC_KEY_STAGING,
	INTEGRATION_OUTREACH_APP_ID,
	INTEGRATION_OUTREACH_APP_SECRET,
	INTEGRATION_FLOWDOCK_TOKEN,
	INTEGRATION_FLOWDOCK_SIGNATURE_KEY,
};
