const SERVER_HOST = 'http://api.ly.fish.local';
const SERVER_PORT = '80';
const HTTP_WORKER_PORT = 8002;
const HTTP_TIMEOUT = 60;
const HTTP_HEADERS_TIMEOUT = 60;
const HTTP_REQUEST_TIMEOUT = 60;

export {
	SERVER_HOST,
	SERVER_PORT,
	HTTP_WORKER_PORT,
	HTTP_TIMEOUT,
	HTTP_HEADERS_TIMEOUT,
	HTTP_REQUEST_TIMEOUT,
};
