const POSTGRES_HOST = 'postgres';
const POSTGRES_PORT = '5432';
const POSTGRES_DATABASE = 'jellyfish';
const POSTGRES_USER = 'docker';
const POSTGRES_PASSWORD = 'docker';

export {
	POSTGRES_HOST,
	POSTGRES_PORT,
	POSTGRES_DATABASE,
	POSTGRES_USER,
	POSTGRES_PASSWORD,
};
