/*
 * Copyright (C) Balena.io - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and confidential.
 */

const REGISTRY_TOKEN_AUTH_CERT_ISSUER = 'api.ly.fish.local';
const REGISTRY_TOKEN_AUTH_CERT_KEY =
	'LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU4xWUw1WVRjb3NVVnhHdXlXMGt4cGE0ekxzbEpGQ2JvZUxIUWlpaW1vTkhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFR0RRQ2FpK1FnNG9GZE9HMXZNdWdtMFA5bTViSUR3R29MNjg1aGVYR0hwZWJVblgxOGQvYwpQUTZGbDBQaklQam9iUzlCNW5oSTF1Y0p3MW8vclE2UXdnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=';
const REGISTRY_TOKEN_AUTH_CERT_KID =
	'UkNVNTo2Q1RaOkJITjc6RlBCUjpKWUJIOjVHRVI6QVdQSDpIRk9aOjZaT0c6VVUzTzo3Q0gzOjZFU0sK';
const REGISTRY_TOKEN_AUTH_JWT_ALGO = 'ES256';
const REGISTRY_HOST = 'registry.ly.fish.local';

export {
	REGISTRY_HOST,
	REGISTRY_TOKEN_AUTH_JWT_ALGO,
	REGISTRY_TOKEN_AUTH_CERT_KID,
	REGISTRY_TOKEN_AUTH_CERT_KEY,
	REGISTRY_TOKEN_AUTH_CERT_ISSUER,
};
