const REGISTRY_TOKEN_AUTH_CERT_ISSUER = 'api.ly.fish.local';
const REGISTRY_TOKEN_AUTH_CERT_KEY = '';
const REGISTRY_TOKEN_AUTH_CERT_KID = '';
const REGISTRY_TOKEN_AUTH_JWT_ALGO = 'ES256';
const REGISTRY_HOST = 'registry.ly.fish.local';

export {
	REGISTRY_HOST,
	REGISTRY_TOKEN_AUTH_JWT_ALGO,
	REGISTRY_TOKEN_AUTH_CERT_KID,
	REGISTRY_TOKEN_AUTH_CERT_KEY,
	REGISTRY_TOKEN_AUTH_CERT_ISSUER,
};
