const HUBOT__EMAIL_HASHTAGS__HASHTAGS = '{"access":"access", "order":"order"}';
const HUBOT__EMAIL_HASHTAGS__DOMAIN = 'foo.bar';
const HUBOT__ORDER_HASHTAG_FOOTER = '';
const HUBOT__EMAIL_HASHTAGS__UPPER_LIMIT = '64';
const HUBOT__EMAIL_HASHTAGS__LOWER_LIMIT = '4';
const HUBOT_SMTP_USER = 'hubot@foo.bar';
const HUBOT_SMTP_PASSWORD = 'buz';
const HUBOT_SMTP_SERVER = 'smtp.foo.bar';
const HUBOT__LEAVE__CALAMARI_INSTANCE = 'balena';
const HUBOT__LEAVE__CALAMARI_TOKEN = 'foobar';

export {
	HUBOT__EMAIL_HASHTAGS__HASHTAGS,
	HUBOT__EMAIL_HASHTAGS__DOMAIN,
	HUBOT__ORDER_HASHTAG_FOOTER,
	HUBOT__EMAIL_HASHTAGS__UPPER_LIMIT,
	HUBOT__EMAIL_HASHTAGS__LOWER_LIMIT,
	HUBOT_SMTP_USER,
	HUBOT_SMTP_PASSWORD,
	HUBOT_SMTP_SERVER,
	HUBOT__LEAVE__CALAMARI_INSTANCE,
	HUBOT__LEAVE__CALAMARI_TOKEN,
};
